databases:
  - name: xpathedgehr-db
    plan: free
    databaseName: xpathedgehr_db
    user: xpathedgehr_db_user

services:
  - type: web
    plan: free
    name: horilla
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn horilaa.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: xpathedgehr-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4